spring:
  application:
    name: resume-api
  # profiles:
  #   default: dev

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: com.pedro.resumeapi.ai.kafka.AiJobRequestedMessageSerializer

  jpa:
    hibernate:
      ddl-auto: validate

  flyway:
    enabled: true

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI}
      uuid-representation: standard

app:
  ai-jobs:
    topic: ${KAFKA_PREFIX:}resume-ai-jobs
  storage:
    backend: S3
    local-dir: ${APP_STORAGE_LOCAL_DIR:/tmp/resume-storage}
    s3:
      region: ${AWS_REGION}
      bucket: ${AWS_BUCKET}
      cloudfront-url: ${CLOUDFRONT_URL}
      presign-expiration: ${APP_STORAGE_S3_PRESIGN_EXPIRATION}
  jwt:
    secret: ${APP_JWT_SECRET}
    issuer: ${APP_JWT_ISSUER}
    expMinutes: ${APP_JWT_EXPMINUTES}
  # secret: mySecretKeyMySecretKeyMySecretKeyMySecretKeyMySecretKey

  security:
    rate-limit:
      share:
        enabled: false
        requests: 120
        window: 1m

logging:
  level:
    root: WARN
    # org.springframework.security: DEBUG
